"""Read tracked source files and produce a reviewable documentation snapshot.

Never imports the scientific packages. All generated output stays in this repo.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parents[1]
ALLOWED = {"casm_io", "casm_vis_analysis", "casm_calibrator"}


def git(repo: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(repo), *args], text=True).strip()


def signature(node: ast.AST) -> str:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        result = f"{node.name}({ast.unparse(node.args)})"
        if node.returns:
            result += " -> " + ast.unparse(node.returns)
        return result
    bases = ", ".join(ast.unparse(base) for base in node.bases)
    return f"class {node.name}" + (f"({bases})" if bases else "")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true", help="Verify pinned files without refreshing documentation")
    args = parser.parse_args()
    if args.check:
        snapshot = json.loads((ROOT / "source-snapshot.json").read_text())
        drift = []
        for package in snapshot["packages"]:
            name = package["repository"]
            if name not in ALLOWED:
                raise ValueError(f"Repository outside approved scope: {name}")
            repo = (args.source_root / name).resolve()
            if git(repo, "rev-parse", "HEAD") != package["revision"]:
                drift.append(f"{name}: baseline revision changed")
            for relative, expected in package["files"].items():
                path = (repo / relative).resolve()
                if not path.is_relative_to(repo):
                    raise ValueError("Source path escaped repository")
                if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != expected:
                    drift.append(f"{name}/{relative}: content changed")
        if drift:
            raise SystemExit("Documentation source drift:\n" + "\n".join(drift))
        print("OK: pinned revisions and source hashes match")
        return
    packages = json.loads((ROOT / "sources.json").read_text())["packages"]
    snapshot = {"schema": 1, "packages": []}
    source_page = ["# Sources and verification\n", "This preview uses explicitly inspected source checkouts. Git revisions identify the baseline; SHA-256 hashes identify the actual files read. Untracked source files are excluded.\n", "| Package | Baseline revision | Tracked working-tree changes |", "|---|---|---|"]
    upstream = ["# Existing manuals\n", "These are unedited, tracked source manuals copied for reference. They may contain historical defaults or unresolved inconsistencies. Prefer the curated guides for this preview; use these downloads to examine the original wording. Relative links inside downloaded Markdown may require the original checkout.\n"]
    for package in packages:
        name = package["repo"]
        if name not in ALLOWED:
            raise ValueError(f"Repository is outside approved scope: {name}")
        repo = (args.source_root / name).resolve()
        tracked = set(git(repo, "ls-files").splitlines())
        revision = git(repo, "rev-parse", "HEAD")
        remote = git(repo, "remote", "get-url", "origin").removesuffix(".git")
        changes = git(repo, "diff", "HEAD", "--name-only").splitlines()
        record = {"repository": name, "revision": revision, "remote": remote,
                  "tracked_changes": changes, "files": {}}

        def read(relative: str) -> bytes:
            if relative not in tracked:
                raise ValueError(f"Not a tracked source: {name}/{relative}")
            path = (repo / relative).resolve()
            if not path.is_relative_to(repo):
                raise ValueError("Source path escaped repository")
            data = path.read_bytes()
            record["files"][relative] = hashlib.sha256(data).hexdigest()
            return data

        metadata = tomllib.loads(read("pyproject.toml").decode())
        record["package_version"] = metadata.get("project", {}).get("version", "unspecified")
        page = [f"# {name}: API and commands\n", f"Source baseline: `{revision[:12]}`. Generated by static parsing; no package imports. These are selected defining modules, not a claim that every symbol is re-exported at the package root. Docstrings below are unedited source text and may need scientific qualification.\n", "## Command entry points\n", "| Command | Entry point |", "|---|---|"]
        for command, target in metadata.get("project", {}).get("scripts", {}).items():
            page.append(f"| `{command}` | `{target}` |")
        page.append("\nSome commands write products or configuration. Consult the workflow before execution.\n")
        for relative in package["modules"]:
            source = read(relative).decode()
            module = relative.removeprefix("src/").removesuffix(".py").replace("/", ".")
            source_copy = ROOT / "docs" / "_code" / Path(*module.split(".")).with_suffix(".py")
            source_copy.parent.mkdir(parents=True, exist_ok=True)
            source_copy.write_text(source)
            page.append(f"\n## {module}\n")
            page.append(f"```{{py:currentmodule}} {module}\n```\n")
            # The hash captures dirty bytes; links explicitly target the git baseline.
            page.append(f"[Baseline source]({remote}/blob/{revision}/{relative}) · snapshot hash `{record['files'][relative][:12]}`\n")
            for node in ast.parse(source).body:
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) or node.name.startswith("_"):
                    continue
                kind = "class" if isinstance(node, ast.ClassDef) else "function"
                declaration = signature(node).removeprefix("class ")
                page += [f"\n### {node.name}\n", f"```{{py:{kind}}} {declaration}\n```\n"]
                doc = ast.get_docstring(node)
                if doc:
                    page.append("````text\n" + doc + "\n````\n")
                if isinstance(node, ast.ClassDef):
                    for method in node.body:
                        if isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)) and (not method.name.startswith("_") or method.name == "__init__"):
                            page.append(f"```{{py:method}} {node.name}.{signature(method)}\n```\n")
                            method_doc = ast.get_docstring(method)
                            if method_doc:
                                page.append("````text\n" + method_doc + "\n````\n")
        dest = ROOT / "docs" / "packages" / f"{package['slug']}-api.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text("\n".join(page))
        upstream.append(f"\n## {name}\n")
        for relative in sorted(tracked):
            if (relative.startswith("docs/") and relative.endswith(".md")) or relative in {"README.md", "LICENSE", "LICENSE.md", "LICENSE.txt"}:
                data = read(relative)
                target = ROOT / "docs" / "_downloads" / name / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
                upstream.append(f"- {{download}}`{relative} <_downloads/{name}/{relative}>`")
            elif relative.endswith(".py") or relative in {"CLAUDE.md", "AGENTS.md"} or (relative.endswith(".json") and "/configs/" in relative):
                read(relative)
        snapshot["packages"].append(record)
        source_page.append(f"| {name} | `{revision[:12]}` | {len(changes)} |")
    source_page += ["\n## Verification boundaries\n", "- API signatures and command entry points are extracted from tracked source.\n- Existing manuals are preserved as downloads; curated pages identify known discrepancies.\n- Example syntax and selected installed signatures are checked separately. Real-data examples remain illustrative unless explicitly marked otherwise.\n- These documentation checks do not validate telescope state, scientific sensitivity, or an operational recipe.\n- Dirty notebook changes in a source checkout do not become undocumented defaults. File hashes in the snapshot identify exactly what was consumed.\n", "## Reproducing the snapshot\n", "The repository contains `sources.json` (the allowlist and selected modules), `source-snapshot.json` (revisions and file hashes), and `scripts/snapshot_sources.py`. Refresh explicitly, review the diff, then rebuild. The committed pages and downloads can build without source checkouts.\n"]
    snapshot["snapshot_id"] = hashlib.sha256(json.dumps(snapshot["packages"], sort_keys=True).encode()).hexdigest()[:16]
    source_page += ["\n## Version policy\n", f"Documentation snapshot: `{snapshot['snapshot_id']}`. Coverage starts with this preview; no historical-version backfill is planned. Package version strings alone are insufficient to identify these checkouts, so revision plus file hashes are authoritative for this documentation.\n", "Run `python scripts/snapshot_sources.py --source-root /home/casm/software/dev --check` before refreshing to detect source drift. Future releases should pair a reviewed software revision with a documentation snapshot. Snapshot generation does not edit source repositories.\n", "Source instruction updates may be committed locally before publication. GitHub baseline links for those commits become available after the owner pushes; the built-in source views work from the recorded copies now.\n"]
    (ROOT / "source-snapshot.json").write_text(json.dumps(snapshot, indent=2) + "\n")
    (ROOT / "docs" / "sources.md").write_text("\n".join(source_page))
    (ROOT / "docs" / "upstream.md").write_text("\n".join(upstream) + "\n")
    print(f"Snapshotted {len(snapshot['packages'])} repositories without importing them")


if __name__ == "__main__":
    main()
